// This file is generated by npm run build:icons

export type IconName =
  | "caret-sort"
  | "check"
  | "chevron-down"
  | "chevron-left"
  | "chevron-right"
  | "chevron-up"
  | "cross"
  | "dashboard"
  | "dot-filled"
  | "employee"
  | "feedback"
  | "input"
  | "lab-timer"
  | "laptop"
  | "magnifying-glass"
  | "moon"
  | "pin"
  | "project"
  | "setting"
  | "sun"
  | "table";
