import { PayrollComponent } from "@/components/payroll/payroll-component";

const employeesDemo = [
  {
    name: "John Doe",
    paid_days: 25,
    gross_pay: 5000,
    taxes: 800,
    discount: 200,
    bonus: 500,
    email: "johndoe@example.com",
    mobile_number: "123-456-7890",
    reimbursements: 150,
    company_name: "TechCorp Inc.",
    site_name: "Downtown Office",
    area: "New York",
    net_pay: 4650,
  },
  {
    name: "Jane Smith",
    paid_days: 28,
    gross_pay: 6000,
    taxes: 1000,
    discount: 300,
    bonus: 700,
    email: "janesmith@example.com",
    mobile_number: "987-654-3210",
    reimbursements: 200,
    company_name: "Innovatech Solutions",
    site_name: "Main Campus",
    area: "San Francisco",
    net_pay: 5600,
  },
  {
    name: "Alice Brown",
    paid_days: 30,
    gross_pay: 7000,
    taxes: 1200,
    discount: 400,
    bonus: 800,
    email: "alicebrown@example.com",
    mobile_number: "456-789-1234",
    reimbursements: 300,
    company_name: "BrightFuture LLC",
    site_name: "Tech Park",
    area: "Chicago",
    net_pay: 6500,
  },
  {
    name: "Bob Johnson",
    paid_days: 22,
    gross_pay: 4500,
    taxes: 700,
    discount: 150,
    bonus: 400,
    email: "bobjohnson@example.com",
    mobile_number: "321-654-9870",
    reimbursements: 100,
    company_name: "NextGen Systems",
    site_name: "North Hub",
    area: "Seattle",
    net_pay: 4150,
  },
  {
    name: "Emily Davis",
    paid_days: 27,
    gross_pay: 5500,
    taxes: 900,
    discount: 250,
    bonus: 600,
    email: "emilydavis@example.com",
    mobile_number: "789-123-4567",
    reimbursements: 200,
    company_name: "Visionary Tech",
    site_name: "West Center",
    area: "Austin",
    net_pay: 5150,
  },
  {
    name: "Chris Evans",
    paid_days: 26,
    gross_pay: 4800,
    taxes: 700,
    discount: 300,
    bonus: 450,
    email: "chrisevans@example.com",
    mobile_number: "231-456-9876",
    reimbursements: 120,
    company_name: "TechNova Inc.",
    site_name: "Innovation Hub",
    area: "Boston",
    net_pay: 4870,
  },
  {
    name: "Sarah Lee",
    paid_days: 29,
    gross_pay: 6300,
    taxes: 1000,
    discount: 400,
    bonus: 750,
    email: "sarahlee@example.com",
    mobile_number: "741-852-9630",
    reimbursements: 220,
    company_name: "FusionTech",
    site_name: "Corporate Tower",
    area: "Los Angeles",
    net_pay: 5870,
  },
  {
    name: "David Miller",
    paid_days: 24,
    gross_pay: 5200,
    taxes: 850,
    discount: 250,
    bonus: 300,
    email: "davidmiller@example.com",
    mobile_number: "852-963-7410",
    reimbursements: 180,
    company_name: "TechWave",
    site_name: "South Campus",
    area: "Denver",
    net_pay: 4680,
  },
  {
    name: "Anna Johnson",
    paid_days: 25,
    gross_pay: 5600,
    taxes: 900,
    discount: 300,
    bonus: 600,
    email: "annajohnson@example.com",
    mobile_number: "963-741-8520",
    reimbursements: 210,
    company_name: "BrightTech",
    site_name: "East Office",
    area: "Orlando",
    net_pay: 5210,
  },
  {
    name: "Michael Brown",
    paid_days: 28,
    gross_pay: 6100,
    taxes: 1100,
    discount: 250,
    bonus: 500,
    email: "michaelbrown@example.com",
    mobile_number: "147-258-3690",
    reimbursements: 190,
    company_name: "FutureTech",
    site_name: "Innovation Center",
    area: "Phoenix",
    net_pay: 5440,
  },
  {
    name: "Sophia Wilson",
    paid_days: 27,
    gross_pay: 5900,
    taxes: 950,
    discount: 300,
    bonus: 550,
    email: "sophiawilson@example.com",
    mobile_number: "258-369-1470",
    reimbursements: 220,
    company_name: "VisionEdge",
    site_name: "Tech District",
    area: "Dallas",
    net_pay: 5420,
  },
  {
    name: "James White",
    paid_days: 26,
    gross_pay: 5300,
    taxes: 800,
    discount: 200,
    bonus: 450,
    email: "jameswhite@example.com",
    mobile_number: "369-147-2580",
    reimbursements: 170,
    company_name: "AlphaTech",
    site_name: "Central Office",
    area: "Houston",
    net_pay: 4920,
  },
  {
    name: "Olivia Harris",
    paid_days: 30,
    gross_pay: 6400,
    taxes: 1050,
    discount: 400,
    bonus: 700,
    email: "oliviaharris@example.com",
    mobile_number: "147-369-2580",
    reimbursements: 240,
    company_name: "BetaInnovations",
    site_name: "Metro Hub",
    area: "Miami",
    net_pay: 5890,
  },
  {
    name: "Ethan Clark",
    paid_days: 23,
    gross_pay: 4700,
    taxes: 750,
    discount: 200,
    bonus: 300,
    email: "ethanclark@example.com",
    mobile_number: "258-147-3690",
    reimbursements: 150,
    company_name: "OmniTech",
    site_name: "Research Center",
    area: "Portland",
    net_pay: 4200,
  },
  {
    name: "Ava Martinez",
    paid_days: 29,
    gross_pay: 6500,
    taxes: 1150,
    discount: 300,
    bonus: 800,
    email: "avamartinez@example.com",
    mobile_number: "369-258-1470",
    reimbursements: 250,
    company_name: "TechCore",
    site_name: "Downtown Tower",
    area: "San Diego",
    net_pay: 6100,
  },
  {
    name: "Lucas Robinson",
    paid_days: 24,
    gross_pay: 4900,
    taxes: 800,
    discount: 250,
    bonus: 350,
    email: "lucasrobinson@example.com",
    mobile_number: "852-741-9630",
    reimbursements: 180,
    company_name: "NextStep",
    site_name: "West Center",
    area: "Nashville",
    net_pay: 4580,
  },
  {
    name: "Mia Walker",
    paid_days: 27,
    gross_pay: 5700,
    taxes: 900,
    discount: 300,
    bonus: 500,
    email: "miawalker@example.com",
    mobile_number: "963-852-7410",
    reimbursements: 200,
    company_name: "PioneerTech",
    site_name: "East Campus",
    area: "Charlotte",
    net_pay: 5200,
  },
  {
    name: "Daniel Hall",
    paid_days: 28,
    gross_pay: 6000,
    taxes: 1000,
    discount: 350,
    bonus: 600,
    email: "danielhall@example.com",
    mobile_number: "789-456-1230",
    reimbursements: 250,
    company_name: "TechSphere",
    site_name: "Corporate HQ",
    area: "Atlanta",
    net_pay: 5500,
  },
  {
    name: "Ella Carter",
    paid_days: 25,
    gross_pay: 5100,
    taxes: 850,
    discount: 200,
    bonus: 400,
    email: "ellacarter@example.com",
    mobile_number: "654-321-9870",
    reimbursements: 150,
    company_name: "SphereTech",
    site_name: "Research Wing",
    area: "Columbus",
    net_pay: 4600,
  },
  {
    name: "Matthew Green",
    paid_days: 30,
    gross_pay: 6800,
    taxes: 1200,
    discount: 500,
    bonus: 800,
    email: "matthewgreen@example.com",
    mobile_number: "741-963-8520",
    reimbursements: 300,
    company_name: "Vanguard Tech",
    site_name: "Tech Hub",
    area: "Detroit",
    net_pay: 6200,
  },
];

const currentDemo = {
  payroll_cost: "12345",
  employeess_net_pay: "12000",
  pending_payments: "10000",
  employees: "1000",
};

const lastMonthDemo = {
  payroll_cost: 15000,
  employeess_net_pay: 1000,
  pending_payments: 2000,
  employees: 1000,
};

const headings = {
  payroll_cost: "PAYROLL COST",
  employeess_net_pay: "EMPLOYEES' NET PAY",
  pending_payments: "PENDING PAYMENTS",
  employees: "TOTAL EMPLOYEES",
};

const calculatePercentageChange = (current: number, previous: number) => {
  return ((current - previous) / previous) * 100;
};

const netPayrollCost = calculatePercentageChange(
  Number(currentDemo.payroll_cost),
  Number(lastMonthDemo.payroll_cost),
);
const netEmployeeNetPay = calculatePercentageChange(
  Number(currentDemo.employeess_net_pay),
  Number(lastMonthDemo.employeess_net_pay),
);
const netPendingPayments = calculatePercentageChange(
  Number(currentDemo.pending_payments),
  Number(lastMonthDemo.pending_payments),
);
const employeediff =
  Number(currentDemo.employees) - Number(lastMonthDemo.employees);

const netDiff = {
  payroll_cost: netPayrollCost,
  employeess_net_pay: netEmployeeNetPay,
  pending_payments: netPendingPayments,
  employees: employeediff,
};

export default function PayrollId() {
  return (
    <PayrollComponent
      data={employeesDemo}
      demo={currentDemo}
      netDiff={netDiff}
      heading={headings}
      lastMonthDemo={lastMonthDemo}
    />
  );
}
